#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3

# Check user parameter
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
    echo "Wrong user"
    exit 1
fi

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a libresonic
if [[ ! $? -eq 0 ]]; then
    exit 1
fi


sudo yunohost app setting libresonic admin_user -v $user

YNH_MAIL=$(sudo yunohost user info $user | grep "mail: " | sed s/'mail: '/''/g)

# Remove trailing "/" for next commands
path=${path%/}

# Install dependencies
echo "Install dependencies ..."
sudo apt-get install -y openjdk-8-jre tomcat8 lame flac faad vorbis-tools ffmpeg xsltproc

# Copy files to the right place


appversion=$(cat upstream_version)
echo "Downloading libresonic $appversion..."
mkdir -p ../libresonic
echo "Extracting to $final_path..."
sudo wget https://jenkins.zifnab.net/job/libresonic/lastSuccessfulBuild/artifact/.repository/org/libresonic/player/libresonic-main/$appversion/libresonic-main-$appversion.war -O /var/lib/tomcat8/webapps/libresonic.war

# Configure tomcat server

sudo mkdir /var/libresonic
sudo mkdir /var/libresonic/transcode
sudo ln -s /usr/bin/lame /var/libresonic/transcode
sudo ln -s /usr/bin/ffmpeg /var/libresonic/transcode



sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/libresonic.conf
sudo echo 'SUBSONIC_ARGS="--context-path=/'$path' --max-memory=190"'>/etc/default/libresonic

sudo sh -c "echo 'LdapAutoShadowing=true' >> /var/libresonic/libresonic.properties"
sudo sh -c "echo 'LdapManagerDn=' >> /var/libresonic/libresonic.properties"
sudo sh -c "echo 'LdapEnabled=true' >> /var/libresonic/libresonic.properties"
sudo sh -c "echo 'LdapUrl=ldap\://localhost\:389/ou\=users,dc\=yunohost,dc\=org' >> /var/libresonic/libresonic.properties"
sudo sh -c "echo 'LdapSearchFilter=(&(objectClass\=mailAccount)(uid\={0}))' >> /var/libresonic/libresonic.properties"




data_path=/home/yunohost.app/libresonic


VERSION="1.10.2"

wget "http://localhost:8080/libresonic/rest/createUser.view?u=admin&p=admin&adminRole=Yes&username=$user&password=a&email=$YNH_MAIL&ldapAuthenticated=Yes&v=$VERSION&c=myapp" > /dev/null 2>&1

wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&adminRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&settingsRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&streamRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&jukebowRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&downloadRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&uploadRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&covertArtRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&commentRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&podcastArtRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/libresonic/rest/updateUser.view?u=admin&p=admin&shareArtRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1


# Reload Nginx and regenerate SSOwat conf

sudo service nginx reload
sudo yunohost app setting libresonic skipped_uris -v "/rest"
sudo yunohost app ssowatconf
