#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a subsonic
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

# Install dependencies
sudo apt-get install -y openjdk-7-jre tomcat7 lame flac faad vorbis-tools ffmpeg

sudo dpkg -i ../sources/subsonic-5.0.beta1.deb

# Copy files to the right place
sudo mkdir /var/subsonic


sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/subsonic.conf


#sudo sh -c "echo 'LdapAutoShadowing=true' >> /var/subsonic/subsonic.properties"
#sudo sh -c "echo 'LdapManagerDn=cn\=admin,dc\=yunohost,dc\=org' >> /var/subsonic/subsonic.properties"
#sudo sh -c "echo 'LdapEnabled=true' >> /var/subsonic/subsonic.properties"
#sudo sh -c "echo 'LdapUrl=ldap\://127.0.0.1\:389/,ou\=users,dc\=yunohost,dc\=org' >> /var/subsonic/subsonic.properties"
#sudo sh -c "echo 'LdapSearchFilter=(&(uid\={0})(memberof\=cn\=users,ou\=users,dc\=yunohost,dc\=org))' >> /var/subsonic/subsonic.properties"





# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting owncloud skipped_uris -v "/"
sudo yunohost app ssowatconf

