#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -u

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

sudo rm /etc/nginx/conf.d/$domain.d/libresonic.conf
sudo rm /etc/default/libresonic

sudo service tomcat8 stop
sudo rm /var/lib/tomcat8/webapps/libresonic.war
sudo rm -r /var/libresonic/
sudo service tomcat8 start

sudo service nginx reload
sudo yunohost app ssowatconf 
