#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

sudo service tomcat8 stop

appversion=$(cat upstream_version)
echo "Downloading libresonic $appversion..."
final_path="/var/lib/tomcat8/webapps/"
sudo wget https://libresonic.org/release/libresonic-v$appversion.war -O ${final_path}libresonic.war

sudo chown -R tomcat8:tomcat8 /var/lib/tomcat8/webapps/
sudo service tomcat8 start
